### ISSUE TITLE
Compilation fails on Elixir 1.7.0-rc.1

### ISSUE THREAD

**Issue by jfornoff** [deadtrickster/prometheus.ex#18]
Hi,

just to let you know: `prometheus_ex` (currently published version on Hex) seems to fail to compile on Elixir 1.7.0-rc.1 (OTP 20).

![image](https://user-images.githubusercontent.com/1319818/42938177-af91e760-8b51-11e8-8821-a9b1cd4db672.png)

Might be related to https://github.com/elixir-lang/elixir/pull/7309
Would love to contribute a fix but I'm not terribly familiar with what the purpose of the Macro is in `prometheus_ex` :-/

**Comment by deadtrickster** [comment]
looks like __CALLER__ argument just needs to be renamed.

**Comment by jfornoff** [comment]
Seems to work just fine :-) I'll prepare a PR.
