### ISSUE TITLE
Return value from Prometheus.Metric.Histogram.observe_duration/2

### ISSUE THREAD

**Issue by darArch** [deadtrickster/prometheus.ex#22]
Hi, we're migrating our platform to run on Kubernetes and as part of that we're transitioning from using Graphite to Prometheus for graphing our metrics. We currently use the library Statix to push metrics to our Graphite server and specifically we use https://hexdocs.pm/statix/Statix.html#c:measure/3 to instrument functions where we measure execution time. Statix.measure/3 allows the return value of the instrumented function to be returned, but unless I'm misunderstanding the correct usage, this doesn't appear to be the case for Prometheus.Metric.Histogram.observe_duration/2?

Could you clarify whether it is possible to return the value of the function passed to Prometheus.Metric.Histogram.observe_duration/2?

**Comment by deadtrickster** [comment]
Hi, https://github.com/deadtrickster/prometheus.ex/blob/master/test/metric/histogram_test.exs#L186 also keep in mind you can also pass a block instead of function.

**Comment by darArch** [comment]
Thanks for this, I'm not sure why I wasn't seeing the same behaviour, I'll check over the rest of the code 👍
